In [2]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.6 MB 2.9 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/12.6 MB 2.8 MB/s eta 0:00:04
   ------ --------------------------------- 2.1/12.6 MB 2.8 MB/s eta 0:00:04
   -------- ------------------------------- 2.6/12.6 MB 2.7 MB/s eta 0:00:04
   ---------- ----------------------------- 3.4/12.6 MB 2.7 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.6 MB 2.7 MB/s eta 0:00:04
   -------------- ------------------------- 4.5/12.6 MB 2.7 MB/s eta 0:00:04
   --------------- ------------------------ 5.0/12.6 MB 2.7 MB/s eta 0:00:03
   ----------------- -----

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [5]:
import numpy as np
print(np.__version__)



2.5.1


In [6]:
import numpy as np


In [7]:
import numpy as np

python_list = [1, 2, 3, 4, 5]
numpy_array = np.array([1, 2, 3, 4, 5])

print("Python List:", python_list)
print("NumPy Array:", numpy_array)

Python List: [1, 2, 3, 4, 5]
NumPy Array: [1 2 3 4 5]


In [8]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50])

print(arr1)

[10 20 30 40 50]


In [9]:
import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("Shape:", arr.shape)
print("Size:", arr.size)
print("Data Type:", arr.dtype)
print("Dimensions:", arr.ndim)

Shape: (2, 3)
Size: 6
Data Type: int64
Dimensions: 2


In [10]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[2])
print(arr[-1])

10
30
50


In [11]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])
print(arr[:3])
print(arr[3:])

[20 30 40]
[10 20 30]
[40 50 60]


In [12]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Addition:", a + b)
print("Subtraction:", a - b)
print("Multiplication:", a * b)
print("Division:", a / b)

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


In [13]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print("Sum:", np.sum(arr))
print("Mean:", np.mean(arr))
print("Maximum:", np.max(arr))
print("Minimum:", np.min(arr))

Sum: 150
Mean: 30.0
Maximum: 50
Minimum: 10


In [14]:
import numpy as np

numbers = np.array([5, 10, 15, 20, 25])

print("Array:", numbers)
print("Shape:", numbers.shape)
print("Size:", numbers.size)
print("Mean:", np.mean(numbers))
print("Maximum:", np.max(numbers))
print("First Element:", numbers[0])
print("Last Element:", numbers[-1])

Array: [ 5 10 15 20 25]
Shape: (5,)
Size: 5
Mean: 15.0
Maximum: 25
First Element: 5
Last Element: 25
